import * as React from 'react';
import '@fortawesome/fontawesome-free/css/all.css';

export const Icons = {
	dashboard: <i className="fas fa-tachometer-alt" />,
	createchar: <i className="fa fa-heart" />,
	soon: <i className="fa fa-hashtag" />,
	missions: <i className="fa fa-exclamation" />,
	covenchat: <i className="fas fa-comment-dots" />,
	profile: <i className="fa fa-flask" />,
	settings: <i className="fa fa-cog" />,
	documentation: <i className="fa fa-book" />,
	apimocking: <i className="fa fa-bug" />,
	coinflipper: <i className="fas fa-dice" />,
	complex: <i className="fa fa-barcode" />,
	plus: <i className="far fa-plus" />,
	minus: <i className="far fa-minus" />,
	plus_alt: <i className="far fa-plus-square" />,
	minus_alt: <i className="far fa-minus-square" />,
	download: <i className="fas fa-download" />,
	calendarPlus: <i className="fas fa-calendar-plus" />,
	calendarMinus: <i className="fas fa-calendar-minus" />,
	calendarTimes: <i className="fas fa-calendar-times" />,
	poweroff: <i className="fas fa-power-off" />,
	bars: <i className="fa fa-bars" />,
	banned: <i className="fas fa-ban" />,
	lockopen: <i className="fas fa-lock-open" />,
	trashcan: <i className="fas fa-trash-alt" />,
	questionmark: <i className="fas fa-question-circle" />,
	exlamation: <i className="fas fa-exclamation-triangle" />,
	file: <i className="fas fa-file" />,
	file_image: <i className="fas fa-file-image" />,
	file_pdf: <i className="fas fa-file-pdf" />,
	file_excel: <i className="fas fa-file-excel" />,
	file_powerpoint: <i className="fas fa-file-powerpoint" />,
	file_word: <i className="fas fa-file-word" />,
	save: <i className="fas fa-save" />,
	close: <i className="fas fa-times" />,
	arrowLeft: <i className="fas fa-arrow-left" />,
	arrowRight: <i className="fas fa-arrow-right" />,
	users: <i className="fas fa-users" />,
	user: <i className="fas fa-user" />,
	check: <i className="fas fa-check" />,
	calendar: <i className="fas fa-calendar-alt" />,
	undo: <i className="fas fa-undo" />,
	redo: <i className="fas fa-redo" />,
	reset: <i className="fas fa-undo" />
};

export default Icons;
